---
- name: Hello World test playbook
  hosts: all
  vars:
    namespace_prefix: zago

  tasks:
    - name: Calling the role to check the environment
      ansible.builtin.include_role:
        name: rhsiqe.skupper.env_shakeout

    - name: Calling the role to generate the namespaces
      ansible.builtin.include_role:
        name: rhsiqe.skupper.generate_namespaces

    - name: Deploying backend and frontend
      ansible.builtin.include_role:
        name: rhsiqe.skupper.deploy_workload

    - name: Installing Skupper
      ansible.builtin.include_role:
        name: rhsiqe.skupper.install_skupper
      when:
        - not skip_skupper_install | default(false) | bool

    - name: Installing Skupper Controller
      ansible.builtin.include_role:
        name: rhsiqe.skupper.install_skupper_controller
      when:
        - not skip_skupper_controller_install | default(false) | bool

    - name: Creating Skupper sites
      ansible.builtin.include_role:
        name: rhsiqe.skupper.skupper_site

    - name: Exposing the connector at the backend (east) site
      ansible.builtin.include_role:
        name: rhsiqe.skupper.expose_connector
      when:
        # Only when the namespace has east in the inventory_hostname
        - "'east' in inventory_hostname"

    - name: Consuming the service at the frontend (west) site
      ansible.builtin.include_role:
        name: rhsiqe.skupper.consume_service
      when:
        # Only when the namespace has west in the inventory_hostname
        - "'west' in inventory_hostname"

    - name: Granting access to the frontend (west) site
      ansible.builtin.include_role:
        name: rhsiqe.skupper.access_grant
      when:
        # Only when the namespace has west in the inventory_hostname
        - "'west' in inventory_hostname"

    - name: Deleting namespaces
      ansible.builtin.include_role:
        name: rhsiqe.skupper.teardown_namespaces
      when:
        - not skip_teardown | default(false) | bool
