---
- name: Host Setup
  hosts: localhost
  roles:
  - rhsiqe.skupper.skupper_test_images
  tasks:
    - name: Host Setup
      ansible.builtin.include_role:
        name: rhsiqe.skupper.host_setup
      when:
        - not skip_host_setup | default(false) | bool

- name: Hello World test playbook
  hosts: all
  roles:
  - rhsiqe.skupper.skupper_test_images
  tasks:
    - name: Setting the temporary directory path
      ansible.builtin.set_fact:
        temp_dir_path: "/tmp/ansible.{{ inventory_hostname }}"

    - name: Creating the temporary directory
      ansible.builtin.file:
        path: "{{ temp_dir_path }}"
        state: directory
        mode: '0700'

    - name: Debugging the temporary directory path
      ansible.builtin.debug:
        var: temp_dir_path

    - name: Environment shakeout
      ansible.builtin.include_role:
        name: rhsiqe.skupper.env_shakeout

    - name: Generating the namespaces
      ansible.builtin.include_role:
        name: rhsiqe.skupper.generate_namespaces

    - name: Installing Skupper
      ansible.builtin.include_role:
        name: rhsiqe.skupper.install_skupper
      when:
        - not skip_skupper_install | default(false) | bool
        - "'west' in inventory_hostname"
      vars:
        install_skupper_install_output_path: "{{ temp_dir_path }}"

    - name: Deploying backend and frontend
      ansible.builtin.include_role:
        name: rhsiqe.skupper.deploy_workload
      vars:
        deploy_workload_output_path: "{{ temp_dir_path }}"

    - name: Creating Skupper sites
      ansible.builtin.include_role:
        name: rhsiqe.skupper.skupper_site
      vars:
        skupper_site_output_path: "{{ temp_dir_path }}"

    - name: Creating connector at east site
      ansible.builtin.include_role:
        name: rhsiqe.skupper.create_connector
      when:
        - "'east' in inventory_hostname"
      vars:
        create_connector_output_path: "{{ temp_dir_path }}"

    - name: Creating listener at the frontend west site
      ansible.builtin.include_role:
        name: rhsiqe.skupper.create_listener
      when:
        - "'west' in inventory_hostname"
      vars:
        create_listener_output_path: "{{ temp_dir_path }}"

    - name: Granting access to the frontend at west site
      ansible.builtin.include_role:
        name: rhsiqe.skupper.access_grant
      when:
        - "'west' in inventory_hostname"
      vars:
        access_grant_output_path: "{{ temp_dir_path }}"

    - name: Exposing the service at the frontend at west site
      ansible.builtin.include_role:
        name: rhsiqe.skupper.expose_service
      when:
        - "'west' in inventory_hostname"

    - name: Linking east site to west site
      ansible.builtin.include_role:
        name: rhsiqe.skupper.link_site
      when:
        - "'east' in inventory_hostname"

    - name: Testing the connectivity between the sites
      ansible.builtin.include_role:
        name: rhsiqe.skupper.run_curl
      vars:
        test_connectivity_output_path: "{{ temp_dir_path }}"
      when:
        - "'west' in inventory_hostname"

    - name: Deleting the test resources
      ansible.builtin.include_role:
        name: rhsiqe.skupper.teardown_test
      when:
        - not skip_teardown | default(false) | bool
