site_name: Skupper Tests Documentation
site_description: Modular and scalable framework to manage Skupper environments with Ansible.
site_author: Rafael Zago
theme:
  name: readthedocs
  user_color_mode_toggle: true
plugins:
  - search
  - markdownextradata
  - include-markdown
  - git-revision-date-localized
nav:
  - Home: index.md
  - Roles:
    - Access Grant: roles/access_grant.md
    - Create Connector: roles/create_connector.md
    - Create Listener: roles/create_listener.md
    - Deploy Job: roles/deploy_job.md
    - Deploy Workload: roles/deploy_workload.md
    - Environment Shakeout: roles/env_shakeout.md
    - Expose Service: roles/expose_service.md
    - Generate Namespaces: roles/generate_namespaces.md
    - Host Setup: roles/host_setup.md
    - Install Skupper: roles/install_skupper.md
    - Link Site: roles/link_site.md
    - Run Curl: roles/run_curl.md
    - Skupper Site: roles/skupper_site.md
    - Skupper Test Images: roles/skupper_test_images.md
    - Teardown Test: roles/teardown_test.md
  - Scenarios:
      - Hello World: scenarios/hello_world.md

