---
galaxy_info:
  author: Rafael Zago
  description: Links two Skupper sites by creating and applying AccessGrant and AccessToken resources to enable cross-namespace communication.
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: 2.1
  galaxy_tags:
    - skupper
    - kubernetes
    - accessgrant
    - accesstoken
    - networking
    - cloud
    - automation

dependencies: []
