namespace: rhsiqe
name: skupper
version: 0.1.2
readme: README.md
authors:
  - Rafael Zago <rafaelvzago@gmail.com>
description: This is a collection to test the skupper V2.
repository: https://github.com/rafaelvzago/skupper-tests.git
