---
# Default variables for access_grant role
access_grant_name: my-grant
access_grant_redemptions_allowed: 10
access_grant_expiration_window: 1h
access_grant_state: present
access_grant_template: access-grant.yml.j2
