---
- name: Download Helm installation script
  ansible.builtin.get_url:
    url: "{{ host_setup_helm_script_url }}"
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: Install Helm using script
  ansible.builtin.command: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm

- name: Remove Helm installation script
  ansible.builtin.file:
    path: /tmp/get_helm.sh
    state: absent

- name: Verify Helm installation
  ansible.builtin.command: /usr/local/bin/helm version
  register: helm_version_result
