---
- name: Install Skupper
  hosts: hello-world
  roles:
    - roles/skupper-install

  tasks:
    - name: Generate a lowercase prefix
      set_fact:
        prefix: "{{ lookup('password', '/dev/null chars=ascii_lowercase length=3') }}"

    - name: Debug the prefix
      debug:
        msg: "Prefix: {{ prefix }}"

    - name: Create namespace hello-world-west
      command: kubectl create namespace {{ prefix }}-hello-world-west
      register: west_ns

    - name: Create namespace hello-world-east
      command: kubectl create namespace {{ prefix }}-hello-world-east
      register: east_ns

    - name: Extracting only the namespace name
      set_fact:
        west_ns: "{{ west_ns.stdout.split('/')[1].split()[0] }}"
        east_ns: "{{ east_ns.stdout.split('/')[1].split()[0] }}"

    - name: Print the namespace names
      debug:
        msg: "West: {{ west_ns }} - East: {{ east_ns }}"

    - name: Deploying Frontend into the west namespace
      command: kubectl create deployment frontend --image={{ images.frontend }} -n {{ west_ns }}

    - name: Deploying Backend into the west namespace
      command: kubectl create deployment backend --image={{ images.backend }} -n {{ east_ns }}

    - name: Apply Skupper West Site YAML
      k8s:
        state: present
        src: files/west-site.yml
        namespace: "{{ west_ns }}"

    - name: Apply Skupper East Site YAML
      k8s:
        state: present
        src: files/east-site.yml
        namespace: "{{ east_ns }}"

    - name: Waiting to all pods to be ready on West
      k8s_info:
        kind: Pod
        namespace: "{{ west_ns }}"
      register: west_pods
      until: west_pods.resources | map(attribute='status.phase') | select('equalto', 'Running') | list | length == 1
      retries: 30
      delay: 10

    - name: Waiting to all pods to be ready on East
      k8s_info:
        kind: Pod
        namespace: "{{ east_ns }}"
      register: east_pods
      until: east_pods.resources | map(attribute='status.phase') | select('equalto', 'Running') | list | length == 1
      retries: 30
      delay: 10

    - name: Exposing Backend in the east namespace
      k8s:
        state: present
        src: files/backend-connector.yml
        namespace: "{{ east_ns }}"

    - name: Consuming Backend in the west namespace
      k8s:
        state: present
        src: files/frontend-listener.yml
        namespace: "{{ west_ns }}"

    - name: Calling role to link the two sites
      include_role:
        name: skupper-link-sites
      vars:
        source_namespace: "{{ west_ns }}"
        target_namespace: "{{ east_ns }}"
        access_grant_name: my-grant
        access_token_name: my-access-token

    - name: Creating the Frontend Service
      command: kubectl expose deployment frontend --port=8080 --target-port=8080 --type=LoadBalancer -n {{ west_ns }}
      register: frontend_service

    - name: Run curl command in Kubernetes with retries
      shell: |
        kubectl run curl --image=quay.io/rzago/curl-telnet -n {{ west_ns }} \
        --restart=Never --rm -i --tty -- curl backend:8080/api/hello
      register: curl_command
      retries: 5
      delay: 10
      until: curl_command.rc == 0

    - name: Debug the curl command
      debug:
        msg: "{{ curl_command.stdout_lines }}"

    - name: Tear down the environment
      command: kubectl delete namespace {{ west_ns }} {{ east_ns }}
      ignore_errors: true
