---
- name: Test connection to all Kubernetes clusters and validate connection
  hosts: k8s_clusters
  gather_facts: no
  vars:
    kubeconfig_path: "{{ kubeconfig | expanduser }}"  # Expands ~ to the full path

  tasks:
    - name: Printing the kubeconfig path
      debug:
        msg: "Kubeconfig path: {{ kubeconfig_path }}"

    - name: Validate connection to Kubernetes cluster
      kubernetes.core.k8s_cluster_info:
        kubeconfig: "{{ kubeconfig_path }}"
      register: server_info
      ignore_errors: yes  # Continue even if a connection fails

    - name: Confirm connection to cluster
      assert:
        that:
          - server_info is defined
        success_msg: "Successfully connected to {{ inventory_hostname }}"
        fail_msg: "Failed to connect to {{ inventory_hostname }}"
