---
- name: Printing all the role variables
  debug:
    msg:
      - "skupper_repository: {{ skupper_repository }}"
      - "skupper_branch: {{ skupper_branch }}"
      - "skupper_controller_manifest: {{ skupper_controller_manifest }}"
    
- name: Create a temporary directory for the Skupper repository
  tempfile:
    state: directory
    suffix: skupper_repo
  register: temp_repo_dir

- name: Clone the Skupper repository
  git:
    repo: "{{ skupper_repository }}"
    dest: "{{ temp_repo_dir.path }}"
    version: "{{ skupper_branch }}"
    depth: 1

- name: Find Skupper CRD files
  find:
    paths: "{{ temp_repo_dir.path }}/api/types/crds"
    patterns: "*.yaml"
  register: crd_files

- name: Install Skupper CRDs
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfigs[inventory_hostname] }}"
    src: "{{ item.path }}"
  loop: "{{ crd_files.files }}"
  register: skupper_crd_results

- name: Install the Skupper Controller
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfigs[inventory_hostname] }}"
    src: "{{ skupper_controller_manifest }}"
    state: present
  register: skupper_controller_results
