name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - zago
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install MkDocs and dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-markdownextradata-plugin mkdocs-include-markdown-plugin mkdocs-git-revision-date-localized-plugin

      # Step 4: Build the site
      - name: Build MkDocs site
        run: mkdocs build --clean

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs  # This is where MkDocs outputs built files

